#ifndef _SYSCALL_STR_H
#define _SYSCALL_STR_H

#include "asm/unistd.h"

extern const char* syscall_str[500];

#define SYS_read __NR_read
#define SYS_write __NR_write
#define SYS_open __NR_open
#define SYS_close __NR_close
#define SYS_stat __NR_stat
#define SYS_fstat __NR_fstat
#define SYS_lstat __NR_lstat
#define SYS_poll __NR_poll
#define SYS_lseek __NR_lseek
#define SYS_mmap __NR_mmap
#define SYS_mprotect __NR_mprotect
#define SYS_munmap __NR_munmap
#define SYS_brk __NR_brk
#define SYS_rt_sigaction __NR_rt_sigaction
#define SYS_rt_sigprocmask __NR_rt_sigprocmask
#define SYS_rt_sigreturn __NR_rt_sigreturn
#define SYS_ioctl __NR_ioctl
#define SYS_pread64 __NR_pread64
#define SYS_pwrite64 __NR_pwrite64
#define SYS_readv __NR_readv
#define SYS_writev __NR_writev
#define SYS_access __NR_access
#define SYS_pipe __NR_pipe
#define SYS_select __NR_select
#define SYS_sched_yield __NR_sched_yield
#define SYS_mremap __NR_mremap
#define SYS_msync __NR_msync
#define SYS_mincore __NR_mincore
#define SYS_madvise __NR_madvise
#define SYS_shmget __NR_shmget
#define SYS_shmat __NR_shmat
#define SYS_shmctl __NR_shmctl
#define SYS_dup __NR_dup
#define SYS_dup2 __NR_dup2
#define SYS_pause __NR_pause
#define SYS_nanosleep __NR_nanosleep
#define SYS_getitimer __NR_getitimer
#define SYS_alarm __NR_alarm
#define SYS_setitimer __NR_setitimer
#define SYS_getpid __NR_getpid
#define SYS_sendfile __NR_sendfile
#define SYS_socket __NR_socket
#define SYS_connect __NR_connect
#define SYS_accept __NR_accept
#define SYS_sendto __NR_sendto
#define SYS_recvfrom __NR_recvfrom
#define SYS_sendmsg __NR_sendmsg
#define SYS_recvmsg __NR_recvmsg
#define SYS_shutdown __NR_shutdown
#define SYS_bind __NR_bind
#define SYS_listen __NR_listen
#define SYS_getsockname __NR_getsockname
#define SYS_getpeername __NR_getpeername
#define SYS_socketpair __NR_socketpair
#define SYS_setsockopt __NR_setsockopt
#define SYS_getsockopt __NR_getsockopt
#define SYS_clone __NR_clone
#define SYS_fork __NR_fork
#define SYS_vfork __NR_vfork
#define SYS_execve __NR_execve
#define SYS_exit __NR_exit
#define SYS_wait4 __NR_wait4
#define SYS_kill __NR_kill
#define SYS_uname __NR_uname
#define SYS_semget __NR_semget
#define SYS_semop __NR_semop
#define SYS_semctl __NR_semctl
#define SYS_shmdt __NR_shmdt
#define SYS_msgget __NR_msgget
#define SYS_msgsnd __NR_msgsnd
#define SYS_msgrcv __NR_msgrcv
#define SYS_msgctl __NR_msgctl
#define SYS_fcntl __NR_fcntl
#define SYS_flock __NR_flock
#define SYS_fsync __NR_fsync
#define SYS_fdatasync __NR_fdatasync
#define SYS_truncate __NR_truncate
#define SYS_ftruncate __NR_ftruncate
#define SYS_getdents __NR_getdents
#define SYS_getcwd __NR_getcwd
#define SYS_chdir __NR_chdir
#define SYS_fchdir __NR_fchdir
#define SYS_rename __NR_rename
#define SYS_mkdir __NR_mkdir
#define SYS_rmdir __NR_rmdir
#define SYS_creat __NR_creat
#define SYS_link __NR_link
#define SYS_unlink __NR_unlink
#define SYS_symlink __NR_symlink
#define SYS_readlink __NR_readlink
#define SYS_chmod __NR_chmod
#define SYS_fchmod __NR_fchmod
#define SYS_chown __NR_chown
#define SYS_fchown __NR_fchown
#define SYS_lchown __NR_lchown
#define SYS_umask __NR_umask
#define SYS_gettimeofday __NR_gettimeofday
#define SYS_getrlimit __NR_getrlimit
#define SYS_getrusage __NR_getrusage
#define SYS_sysinfo __NR_sysinfo
#define SYS_times __NR_times
#define SYS_ptrace __NR_ptrace
#define SYS_getuid __NR_getuid
#define SYS_syslog __NR_syslog
#define SYS_getgid __NR_getgid
#define SYS_setuid __NR_setuid
#define SYS_setgid __NR_setgid
#define SYS_geteuid __NR_geteuid
#define SYS_getegid __NR_getegid
#define SYS_setpgid __NR_setpgid
#define SYS_getppid __NR_getppid
#define SYS_getpgrp __NR_getpgrp
#define SYS_setsid __NR_setsid
#define SYS_setreuid __NR_setreuid
#define SYS_setregid __NR_setregid
#define SYS_getgroups __NR_getgroups
#define SYS_setgroups __NR_setgroups
#define SYS_setresuid __NR_setresuid
#define SYS_getresuid __NR_getresuid
#define SYS_setresgid __NR_setresgid
#define SYS_getresgid __NR_getresgid
#define SYS_getpgid __NR_getpgid
#define SYS_setfsuid __NR_setfsuid
#define SYS_setfsgid __NR_setfsgid
#define SYS_getsid __NR_getsid
#define SYS_capget __NR_capget
#define SYS_capset __NR_capset
#define SYS_rt_sigpending __NR_rt_sigpending
#define SYS_rt_sigtimedwait __NR_rt_sigtimedwait
#define SYS_rt_sigqueueinfo __NR_rt_sigqueueinfo
#define SYS_rt_sigsuspend __NR_rt_sigsuspend
#define SYS_sigaltstack __NR_sigaltstack
#define SYS_utime __NR_utime
#define SYS_mknod __NR_mknod
#define SYS_uselib __NR_uselib
#define SYS_personality __NR_personality
#define SYS_ustat __NR_ustat
#define SYS_statfs __NR_statfs
#define SYS_fstatfs __NR_fstatfs
#define SYS_sysfs __NR_sysfs
#define SYS_getpriority __NR_getpriority
#define SYS_setpriority __NR_setpriority
#define SYS_sched_setparam __NR_sched_setparam
#define SYS_sched_getparam __NR_sched_getparam
#define SYS_sched_setscheduler __NR_sched_setscheduler
#define SYS_sched_getscheduler __NR_sched_getscheduler
#define SYS_sched_get_priority_max __NR_sched_get_priority_max
#define SYS_sched_get_priority_min __NR_sched_get_priority_min
#define SYS_sched_rr_get_interval __NR_sched_rr_get_interval
#define SYS_mlock __NR_mlock
#define SYS_munlock __NR_munlock
#define SYS_mlockall __NR_mlockall
#define SYS_munlockall __NR_munlockall
#define SYS_vhangup __NR_vhangup
#define SYS_modify_ldt __NR_modify_ldt
#define SYS_pivot_root __NR_pivot_root
#define SYS__sysctl __NR__sysctl
#define SYS_prctl __NR_prctl
#define SYS_arch_prctl __NR_arch_prctl
#define SYS_adjtimex __NR_adjtimex
#define SYS_setrlimit __NR_setrlimit
#define SYS_chroot __NR_chroot
#define SYS_sync __NR_sync
#define SYS_acct __NR_acct
#define SYS_settimeofday __NR_settimeofday
#define SYS_mount __NR_mount
#define SYS_umount2 __NR_umount2
#define SYS_swapon __NR_swapon
#define SYS_swapoff __NR_swapoff
#define SYS_reboot __NR_reboot
#define SYS_sethostname __NR_sethostname
#define SYS_setdomainname __NR_setdomainname
#define SYS_iopl __NR_iopl
#define SYS_ioperm __NR_ioperm
#define SYS_create_module __NR_create_module
#define SYS_init_module __NR_init_module
#define SYS_delete_module __NR_delete_module
#define SYS_get_kernel_syms __NR_get_kernel_syms
#define SYS_query_module __NR_query_module
#define SYS_quotactl __NR_quotactl
#define SYS_nfsservctl __NR_nfsservctl
#define SYS_getpmsg __NR_getpmsg
#define SYS_putpmsg __NR_putpmsg
#define SYS_afs_syscall __NR_afs_syscall
#define SYS_tuxcall __NR_tuxcall
#define SYS_security __NR_security
#define SYS_gettid __NR_gettid
#define SYS_readahead __NR_readahead
#define SYS_setxattr __NR_setxattr
#define SYS_lsetxattr __NR_lsetxattr
#define SYS_fsetxattr __NR_fsetxattr
#define SYS_getxattr __NR_getxattr
#define SYS_lgetxattr __NR_lgetxattr
#define SYS_fgetxattr __NR_fgetxattr
#define SYS_listxattr __NR_listxattr
#define SYS_llistxattr __NR_llistxattr
#define SYS_flistxattr __NR_flistxattr
#define SYS_removexattr __NR_removexattr
#define SYS_lremovexattr __NR_lremovexattr
#define SYS_fremovexattr __NR_fremovexattr
#define SYS_tkill __NR_tkill
#define SYS_time __NR_time
#define SYS_futex __NR_futex
#define SYS_sched_setaffinity __NR_sched_setaffinity
#define SYS_sched_getaffinity __NR_sched_getaffinity
#define SYS_set_thread_area __NR_set_thread_area
#define SYS_io_setup __NR_io_setup
#define SYS_io_destroy __NR_io_destroy
#define SYS_io_getevents __NR_io_getevents
#define SYS_io_submit __NR_io_submit
#define SYS_io_cancel __NR_io_cancel
#define SYS_get_thread_area __NR_get_thread_area
#define SYS_lookup_dcookie __NR_lookup_dcookie
#define SYS_epoll_create __NR_epoll_create
#define SYS_epoll_ctl_old __NR_epoll_ctl_old
#define SYS_epoll_wait_old __NR_epoll_wait_old
#define SYS_remap_file_pages __NR_remap_file_pages
#define SYS_getdents64 __NR_getdents64
#define SYS_set_tid_address __NR_set_tid_address
#define SYS_restart_syscall __NR_restart_syscall
#define SYS_semtimedop __NR_semtimedop
#define SYS_fadvise64 __NR_fadvise64
#define SYS_timer_create __NR_timer_create
#define SYS_timer_settime __NR_timer_settime
#define SYS_timer_gettime __NR_timer_gettime
#define SYS_timer_getoverrun __NR_timer_getoverrun
#define SYS_timer_delete __NR_timer_delete
#define SYS_clock_settime __NR_clock_settime
#define SYS_clock_gettime __NR_clock_gettime
#define SYS_clock_getres __NR_clock_getres
#define SYS_clock_nanosleep __NR_clock_nanosleep
#define SYS_exit_group __NR_exit_group
#define SYS_epoll_wait __NR_epoll_wait
#define SYS_epoll_ctl __NR_epoll_ctl
#define SYS_tgkill __NR_tgkill
#define SYS_utimes __NR_utimes
#define SYS_vserver __NR_vserver
#define SYS_mbind __NR_mbind
#define SYS_set_mempolicy __NR_set_mempolicy
#define SYS_get_mempolicy __NR_get_mempolicy
#define SYS_mq_open __NR_mq_open
#define SYS_mq_unlink __NR_mq_unlink
#define SYS_mq_timedsend __NR_mq_timedsend
#define SYS_mq_timedreceive __NR_mq_timedreceive
#define SYS_mq_notify __NR_mq_notify
#define SYS_mq_getsetattr __NR_mq_getsetattr
#define SYS_kexec_load __NR_kexec_load
#define SYS_waitid __NR_waitid
#define SYS_add_key __NR_add_key
#define SYS_request_key __NR_request_key
#define SYS_keyctl __NR_keyctl
#define SYS_ioprio_set __NR_ioprio_set
#define SYS_ioprio_get __NR_ioprio_get
#define SYS_inotify_init __NR_inotify_init
#define SYS_inotify_add_watch __NR_inotify_add_watch
#define SYS_inotify_rm_watch __NR_inotify_rm_watch
#define SYS_migrate_pages __NR_migrate_pages
#define SYS_openat __NR_openat
#define SYS_mkdirat __NR_mkdirat
#define SYS_mknodat __NR_mknodat
#define SYS_fchownat __NR_fchownat
#define SYS_futimesat __NR_futimesat
#define SYS_newfstatat __NR_newfstatat
#define SYS_unlinkat __NR_unlinkat
#define SYS_renameat __NR_renameat
#define SYS_linkat __NR_linkat
#define SYS_symlinkat __NR_symlinkat
#define SYS_readlinkat __NR_readlinkat
#define SYS_fchmodat __NR_fchmodat
#define SYS_faccessat __NR_faccessat
#define SYS_pselect6 __NR_pselect6
#define SYS_ppoll __NR_ppoll
#define SYS_unshare __NR_unshare
#define SYS_set_robust_list __NR_set_robust_list
#define SYS_get_robust_list __NR_get_robust_list
#define SYS_splice __NR_splice
#define SYS_tee __NR_tee
#define SYS_sync_file_range __NR_sync_file_range
#define SYS_vmsplice __NR_vmsplice
#define SYS_move_pages __NR_move_pages
#define SYS_utimensat __NR_utimensat
#define SYS_epoll_pwait __NR_epoll_pwait
#define SYS_signalfd __NR_signalfd
#define SYS_timerfd_create __NR_timerfd_create
#define SYS_eventfd __NR_eventfd
#define SYS_fallocate __NR_fallocate
#define SYS_timerfd_settime __NR_timerfd_settime
#define SYS_timerfd_gettime __NR_timerfd_gettime
#define SYS_accept4 __NR_accept4
#define SYS_signalfd4 __NR_signalfd4
#define SYS_eventfd2 __NR_eventfd2
#define SYS_epoll_create1 __NR_epoll_create1
#define SYS_dup3 __NR_dup3
#define SYS_pipe2 __NR_pipe2
#define SYS_inotify_init1 __NR_inotify_init1
#define SYS_preadv __NR_preadv
#define SYS_pwritev __NR_pwritev
#define SYS_rt_tgsigqueueinfo __NR_rt_tgsigqueueinfo
#define SYS_perf_event_open __NR_perf_event_open
#define SYS_recvmmsg __NR_recvmmsg
#define SYS_fanotify_init __NR_fanotify_init
#define SYS_fanotify_mark __NR_fanotify_mark
#define SYS_prlimit64 __NR_prlimit64
#define SYS_name_to_handle_at __NR_name_to_handle_at
#define SYS_open_by_handle_at __NR_open_by_handle_at
#define SYS_clock_adjtime __NR_clock_adjtime
#define SYS_syncfs __NR_syncfs
#define SYS_sendmmsg __NR_sendmmsg
#define SYS_setns __NR_setns
#define SYS_getcpu __NR_getcpu
#define SYS_process_vm_readv __NR_process_vm_readv
#define SYS_process_vm_writev __NR_process_vm_writev
#define SYS_kcmp __NR_kcmp
#define SYS_finit_module __NR_finit_module
#define SYS_sched_setattr __NR_sched_setattr
#define SYS_sched_getattr __NR_sched_getattr
#define SYS_renameat2 __NR_renameat2
#define SYS_seccomp __NR_seccomp
#define SYS_getrandom __NR_getrandom
#define SYS_memfd_create __NR_memfd_create
#define SYS_kexec_file_load __NR_kexec_file_load
#define SYS_bpf __NR_bpf
#define SYS_execveat __NR_execveat
#define SYS_userfaultfd __NR_userfaultfd
#define SYS_membarrier __NR_membarrier
#define SYS_mlock2 __NR_mlock2
#define SYS_copy_file_range __NR_copy_file_range
#define SYS_preadv2 __NR_preadv2
#define SYS_pwritev2 __NR_pwritev2
#define SYS_pkey_mprotect __NR_pkey_mprotect
#define SYS_pkey_alloc __NR_pkey_alloc
#define SYS_pkey_free __NR_pkey_free
#define SYS_statx __NR_statx
#define SYS_io_pgetevents __NR_io_pgetevents
#define SYS_rseq __NR_rseq
#define SYS_pidfd_send_signal __NR_pidfd_send_signal
#define SYS_io_uring_setup __NR_io_uring_setup
#define SYS_io_uring_enter __NR_io_uring_enter
#define SYS_io_uring_register __NR_io_uring_register
#define SYS_open_tree __NR_open_tree
#define SYS_move_mount __NR_move_mount
#define SYS_fsopen __NR_fsopen
#define SYS_fsconfig __NR_fsconfig
#define SYS_fsmount __NR_fsmount
#define SYS_fspick __NR_fspick
#define SYS_pidfd_open __NR_pidfd_open
#define SYS_clone3 __NR_clone3

// cat /usr/include/x86_64-linux-gnu/asm/unistd_64.h | grep "__NR_" | awk '{ syscall = substr($2, 6); printf "\tsyscall_str[SYS_%s] = \"SYS_%s\";\n", syscall, syscall }'
__attribute__((constructor))
inline void init_syscall_str() {
	syscall_str[SYS_read] = "SYS_read";
	syscall_str[SYS_write] = "SYS_write";
	syscall_str[SYS_open] = "SYS_open";
	syscall_str[SYS_close] = "SYS_close";
	syscall_str[SYS_stat] = "SYS_stat";
	syscall_str[SYS_fstat] = "SYS_fstat";
	syscall_str[SYS_lstat] = "SYS_lstat";
	syscall_str[SYS_poll] = "SYS_poll";
	syscall_str[SYS_lseek] = "SYS_lseek";
	syscall_str[SYS_mmap] = "SYS_mmap";
	syscall_str[SYS_mprotect] = "SYS_mprotect";
	syscall_str[SYS_munmap] = "SYS_munmap";
	syscall_str[SYS_brk] = "SYS_brk";
	syscall_str[SYS_rt_sigaction] = "SYS_rt_sigaction";
	syscall_str[SYS_rt_sigprocmask] = "SYS_rt_sigprocmask";
	syscall_str[SYS_rt_sigreturn] = "SYS_rt_sigreturn";
	syscall_str[SYS_ioctl] = "SYS_ioctl";
	syscall_str[SYS_pread64] = "SYS_pread64";
	syscall_str[SYS_pwrite64] = "SYS_pwrite64";
	syscall_str[SYS_readv] = "SYS_readv";
	syscall_str[SYS_writev] = "SYS_writev";
	syscall_str[SYS_access] = "SYS_access";
	syscall_str[SYS_pipe] = "SYS_pipe";
	syscall_str[SYS_select] = "SYS_select";
	syscall_str[SYS_sched_yield] = "SYS_sched_yield";
	syscall_str[SYS_mremap] = "SYS_mremap";
	syscall_str[SYS_msync] = "SYS_msync";
	syscall_str[SYS_mincore] = "SYS_mincore";
	syscall_str[SYS_madvise] = "SYS_madvise";
	syscall_str[SYS_shmget] = "SYS_shmget";
	syscall_str[SYS_shmat] = "SYS_shmat";
	syscall_str[SYS_shmctl] = "SYS_shmctl";
	syscall_str[SYS_dup] = "SYS_dup";
	syscall_str[SYS_dup2] = "SYS_dup2";
	syscall_str[SYS_pause] = "SYS_pause";
	syscall_str[SYS_nanosleep] = "SYS_nanosleep";
	syscall_str[SYS_getitimer] = "SYS_getitimer";
	syscall_str[SYS_alarm] = "SYS_alarm";
	syscall_str[SYS_setitimer] = "SYS_setitimer";
	syscall_str[SYS_getpid] = "SYS_getpid";
	syscall_str[SYS_sendfile] = "SYS_sendfile";
	syscall_str[SYS_socket] = "SYS_socket";
	syscall_str[SYS_connect] = "SYS_connect";
	syscall_str[SYS_accept] = "SYS_accept";
	syscall_str[SYS_sendto] = "SYS_sendto";
	syscall_str[SYS_recvfrom] = "SYS_recvfrom";
	syscall_str[SYS_sendmsg] = "SYS_sendmsg";
	syscall_str[SYS_recvmsg] = "SYS_recvmsg";
	syscall_str[SYS_shutdown] = "SYS_shutdown";
	syscall_str[SYS_bind] = "SYS_bind";
	syscall_str[SYS_listen] = "SYS_listen";
	syscall_str[SYS_getsockname] = "SYS_getsockname";
	syscall_str[SYS_getpeername] = "SYS_getpeername";
	syscall_str[SYS_socketpair] = "SYS_socketpair";
	syscall_str[SYS_setsockopt] = "SYS_setsockopt";
	syscall_str[SYS_getsockopt] = "SYS_getsockopt";
	syscall_str[SYS_clone] = "SYS_clone";
	syscall_str[SYS_fork] = "SYS_fork";
	syscall_str[SYS_vfork] = "SYS_vfork";
	syscall_str[SYS_execve] = "SYS_execve";
	syscall_str[SYS_exit] = "SYS_exit";
	syscall_str[SYS_wait4] = "SYS_wait4";
	syscall_str[SYS_kill] = "SYS_kill";
	syscall_str[SYS_uname] = "SYS_uname";
	syscall_str[SYS_semget] = "SYS_semget";
	syscall_str[SYS_semop] = "SYS_semop";
	syscall_str[SYS_semctl] = "SYS_semctl";
	syscall_str[SYS_shmdt] = "SYS_shmdt";
	syscall_str[SYS_msgget] = "SYS_msgget";
	syscall_str[SYS_msgsnd] = "SYS_msgsnd";
	syscall_str[SYS_msgrcv] = "SYS_msgrcv";
	syscall_str[SYS_msgctl] = "SYS_msgctl";
	syscall_str[SYS_fcntl] = "SYS_fcntl";
	syscall_str[SYS_flock] = "SYS_flock";
	syscall_str[SYS_fsync] = "SYS_fsync";
	syscall_str[SYS_fdatasync] = "SYS_fdatasync";
	syscall_str[SYS_truncate] = "SYS_truncate";
	syscall_str[SYS_ftruncate] = "SYS_ftruncate";
	syscall_str[SYS_getdents] = "SYS_getdents";
	syscall_str[SYS_getcwd] = "SYS_getcwd";
	syscall_str[SYS_chdir] = "SYS_chdir";
	syscall_str[SYS_fchdir] = "SYS_fchdir";
	syscall_str[SYS_rename] = "SYS_rename";
	syscall_str[SYS_mkdir] = "SYS_mkdir";
	syscall_str[SYS_rmdir] = "SYS_rmdir";
	syscall_str[SYS_creat] = "SYS_creat";
	syscall_str[SYS_link] = "SYS_link";
	syscall_str[SYS_unlink] = "SYS_unlink";
	syscall_str[SYS_symlink] = "SYS_symlink";
	syscall_str[SYS_readlink] = "SYS_readlink";
	syscall_str[SYS_chmod] = "SYS_chmod";
	syscall_str[SYS_fchmod] = "SYS_fchmod";
	syscall_str[SYS_chown] = "SYS_chown";
	syscall_str[SYS_fchown] = "SYS_fchown";
	syscall_str[SYS_lchown] = "SYS_lchown";
	syscall_str[SYS_umask] = "SYS_umask";
	syscall_str[SYS_gettimeofday] = "SYS_gettimeofday";
	syscall_str[SYS_getrlimit] = "SYS_getrlimit";
	syscall_str[SYS_getrusage] = "SYS_getrusage";
	syscall_str[SYS_sysinfo] = "SYS_sysinfo";
	syscall_str[SYS_times] = "SYS_times";
	syscall_str[SYS_ptrace] = "SYS_ptrace";
	syscall_str[SYS_getuid] = "SYS_getuid";
	syscall_str[SYS_syslog] = "SYS_syslog";
	syscall_str[SYS_getgid] = "SYS_getgid";
	syscall_str[SYS_setuid] = "SYS_setuid";
	syscall_str[SYS_setgid] = "SYS_setgid";
	syscall_str[SYS_geteuid] = "SYS_geteuid";
	syscall_str[SYS_getegid] = "SYS_getegid";
	syscall_str[SYS_setpgid] = "SYS_setpgid";
	syscall_str[SYS_getppid] = "SYS_getppid";
	syscall_str[SYS_getpgrp] = "SYS_getpgrp";
	syscall_str[SYS_setsid] = "SYS_setsid";
	syscall_str[SYS_setreuid] = "SYS_setreuid";
	syscall_str[SYS_setregid] = "SYS_setregid";
	syscall_str[SYS_getgroups] = "SYS_getgroups";
	syscall_str[SYS_setgroups] = "SYS_setgroups";
	syscall_str[SYS_setresuid] = "SYS_setresuid";
	syscall_str[SYS_getresuid] = "SYS_getresuid";
	syscall_str[SYS_setresgid] = "SYS_setresgid";
	syscall_str[SYS_getresgid] = "SYS_getresgid";
	syscall_str[SYS_getpgid] = "SYS_getpgid";
	syscall_str[SYS_setfsuid] = "SYS_setfsuid";
	syscall_str[SYS_setfsgid] = "SYS_setfsgid";
	syscall_str[SYS_getsid] = "SYS_getsid";
	syscall_str[SYS_capget] = "SYS_capget";
	syscall_str[SYS_capset] = "SYS_capset";
	syscall_str[SYS_rt_sigpending] = "SYS_rt_sigpending";
	syscall_str[SYS_rt_sigtimedwait] = "SYS_rt_sigtimedwait";
	syscall_str[SYS_rt_sigqueueinfo] = "SYS_rt_sigqueueinfo";
	syscall_str[SYS_rt_sigsuspend] = "SYS_rt_sigsuspend";
	syscall_str[SYS_sigaltstack] = "SYS_sigaltstack";
	syscall_str[SYS_utime] = "SYS_utime";
	syscall_str[SYS_mknod] = "SYS_mknod";
	syscall_str[SYS_uselib] = "SYS_uselib";
	syscall_str[SYS_personality] = "SYS_personality";
	syscall_str[SYS_ustat] = "SYS_ustat";
	syscall_str[SYS_statfs] = "SYS_statfs";
	syscall_str[SYS_fstatfs] = "SYS_fstatfs";
	syscall_str[SYS_sysfs] = "SYS_sysfs";
	syscall_str[SYS_getpriority] = "SYS_getpriority";
	syscall_str[SYS_setpriority] = "SYS_setpriority";
	syscall_str[SYS_sched_setparam] = "SYS_sched_setparam";
	syscall_str[SYS_sched_getparam] = "SYS_sched_getparam";
	syscall_str[SYS_sched_setscheduler] = "SYS_sched_setscheduler";
	syscall_str[SYS_sched_getscheduler] = "SYS_sched_getscheduler";
	syscall_str[SYS_sched_get_priority_max] = "SYS_sched_get_priority_max";
	syscall_str[SYS_sched_get_priority_min] = "SYS_sched_get_priority_min";
	syscall_str[SYS_sched_rr_get_interval] = "SYS_sched_rr_get_interval";
	syscall_str[SYS_mlock] = "SYS_mlock";
	syscall_str[SYS_munlock] = "SYS_munlock";
	syscall_str[SYS_mlockall] = "SYS_mlockall";
	syscall_str[SYS_munlockall] = "SYS_munlockall";
	syscall_str[SYS_vhangup] = "SYS_vhangup";
	syscall_str[SYS_modify_ldt] = "SYS_modify_ldt";
	syscall_str[SYS_pivot_root] = "SYS_pivot_root";
	syscall_str[SYS__sysctl] = "SYS__sysctl";
	syscall_str[SYS_prctl] = "SYS_prctl";
	syscall_str[SYS_arch_prctl] = "SYS_arch_prctl";
	syscall_str[SYS_adjtimex] = "SYS_adjtimex";
	syscall_str[SYS_setrlimit] = "SYS_setrlimit";
	syscall_str[SYS_chroot] = "SYS_chroot";
	syscall_str[SYS_sync] = "SYS_sync";
	syscall_str[SYS_acct] = "SYS_acct";
	syscall_str[SYS_settimeofday] = "SYS_settimeofday";
	syscall_str[SYS_mount] = "SYS_mount";
	syscall_str[SYS_umount2] = "SYS_umount2";
	syscall_str[SYS_swapon] = "SYS_swapon";
	syscall_str[SYS_swapoff] = "SYS_swapoff";
	syscall_str[SYS_reboot] = "SYS_reboot";
	syscall_str[SYS_sethostname] = "SYS_sethostname";
	syscall_str[SYS_setdomainname] = "SYS_setdomainname";
	syscall_str[SYS_iopl] = "SYS_iopl";
	syscall_str[SYS_ioperm] = "SYS_ioperm";
	syscall_str[SYS_create_module] = "SYS_create_module";
	syscall_str[SYS_init_module] = "SYS_init_module";
	syscall_str[SYS_delete_module] = "SYS_delete_module";
	syscall_str[SYS_get_kernel_syms] = "SYS_get_kernel_syms";
	syscall_str[SYS_query_module] = "SYS_query_module";
	syscall_str[SYS_quotactl] = "SYS_quotactl";
	syscall_str[SYS_nfsservctl] = "SYS_nfsservctl";
	syscall_str[SYS_getpmsg] = "SYS_getpmsg";
	syscall_str[SYS_putpmsg] = "SYS_putpmsg";
	syscall_str[SYS_afs_syscall] = "SYS_afs_syscall";
	syscall_str[SYS_tuxcall] = "SYS_tuxcall";
	syscall_str[SYS_security] = "SYS_security";
	syscall_str[SYS_gettid] = "SYS_gettid";
	syscall_str[SYS_readahead] = "SYS_readahead";
	syscall_str[SYS_setxattr] = "SYS_setxattr";
	syscall_str[SYS_lsetxattr] = "SYS_lsetxattr";
	syscall_str[SYS_fsetxattr] = "SYS_fsetxattr";
	syscall_str[SYS_getxattr] = "SYS_getxattr";
	syscall_str[SYS_lgetxattr] = "SYS_lgetxattr";
	syscall_str[SYS_fgetxattr] = "SYS_fgetxattr";
	syscall_str[SYS_listxattr] = "SYS_listxattr";
	syscall_str[SYS_llistxattr] = "SYS_llistxattr";
	syscall_str[SYS_flistxattr] = "SYS_flistxattr";
	syscall_str[SYS_removexattr] = "SYS_removexattr";
	syscall_str[SYS_lremovexattr] = "SYS_lremovexattr";
	syscall_str[SYS_fremovexattr] = "SYS_fremovexattr";
	syscall_str[SYS_tkill] = "SYS_tkill";
	syscall_str[SYS_time] = "SYS_time";
	syscall_str[SYS_futex] = "SYS_futex";
	syscall_str[SYS_sched_setaffinity] = "SYS_sched_setaffinity";
	syscall_str[SYS_sched_getaffinity] = "SYS_sched_getaffinity";
	syscall_str[SYS_set_thread_area] = "SYS_set_thread_area";
	syscall_str[SYS_io_setup] = "SYS_io_setup";
	syscall_str[SYS_io_destroy] = "SYS_io_destroy";
	syscall_str[SYS_io_getevents] = "SYS_io_getevents";
	syscall_str[SYS_io_submit] = "SYS_io_submit";
	syscall_str[SYS_io_cancel] = "SYS_io_cancel";
	syscall_str[SYS_get_thread_area] = "SYS_get_thread_area";
	syscall_str[SYS_lookup_dcookie] = "SYS_lookup_dcookie";
	syscall_str[SYS_epoll_create] = "SYS_epoll_create";
	syscall_str[SYS_epoll_ctl_old] = "SYS_epoll_ctl_old";
	syscall_str[SYS_epoll_wait_old] = "SYS_epoll_wait_old";
	syscall_str[SYS_remap_file_pages] = "SYS_remap_file_pages";
	syscall_str[SYS_getdents64] = "SYS_getdents64";
	syscall_str[SYS_set_tid_address] = "SYS_set_tid_address";
	syscall_str[SYS_restart_syscall] = "SYS_restart_syscall";
	syscall_str[SYS_semtimedop] = "SYS_semtimedop";
	syscall_str[SYS_fadvise64] = "SYS_fadvise64";
	syscall_str[SYS_timer_create] = "SYS_timer_create";
	syscall_str[SYS_timer_settime] = "SYS_timer_settime";
	syscall_str[SYS_timer_gettime] = "SYS_timer_gettime";
	syscall_str[SYS_timer_getoverrun] = "SYS_timer_getoverrun";
	syscall_str[SYS_timer_delete] = "SYS_timer_delete";
	syscall_str[SYS_clock_settime] = "SYS_clock_settime";
	syscall_str[SYS_clock_gettime] = "SYS_clock_gettime";
	syscall_str[SYS_clock_getres] = "SYS_clock_getres";
	syscall_str[SYS_clock_nanosleep] = "SYS_clock_nanosleep";
	syscall_str[SYS_exit_group] = "SYS_exit_group";
	syscall_str[SYS_epoll_wait] = "SYS_epoll_wait";
	syscall_str[SYS_epoll_ctl] = "SYS_epoll_ctl";
	syscall_str[SYS_tgkill] = "SYS_tgkill";
	syscall_str[SYS_utimes] = "SYS_utimes";
	syscall_str[SYS_vserver] = "SYS_vserver";
	syscall_str[SYS_mbind] = "SYS_mbind";
	syscall_str[SYS_set_mempolicy] = "SYS_set_mempolicy";
	syscall_str[SYS_get_mempolicy] = "SYS_get_mempolicy";
	syscall_str[SYS_mq_open] = "SYS_mq_open";
	syscall_str[SYS_mq_unlink] = "SYS_mq_unlink";
	syscall_str[SYS_mq_timedsend] = "SYS_mq_timedsend";
	syscall_str[SYS_mq_timedreceive] = "SYS_mq_timedreceive";
	syscall_str[SYS_mq_notify] = "SYS_mq_notify";
	syscall_str[SYS_mq_getsetattr] = "SYS_mq_getsetattr";
	syscall_str[SYS_kexec_load] = "SYS_kexec_load";
	syscall_str[SYS_waitid] = "SYS_waitid";
	syscall_str[SYS_add_key] = "SYS_add_key";
	syscall_str[SYS_request_key] = "SYS_request_key";
	syscall_str[SYS_keyctl] = "SYS_keyctl";
	syscall_str[SYS_ioprio_set] = "SYS_ioprio_set";
	syscall_str[SYS_ioprio_get] = "SYS_ioprio_get";
	syscall_str[SYS_inotify_init] = "SYS_inotify_init";
	syscall_str[SYS_inotify_add_watch] = "SYS_inotify_add_watch";
	syscall_str[SYS_inotify_rm_watch] = "SYS_inotify_rm_watch";
	syscall_str[SYS_migrate_pages] = "SYS_migrate_pages";
	syscall_str[SYS_openat] = "SYS_openat";
	syscall_str[SYS_mkdirat] = "SYS_mkdirat";
	syscall_str[SYS_mknodat] = "SYS_mknodat";
	syscall_str[SYS_fchownat] = "SYS_fchownat";
	syscall_str[SYS_futimesat] = "SYS_futimesat";
	syscall_str[SYS_newfstatat] = "SYS_newfstatat";
	syscall_str[SYS_unlinkat] = "SYS_unlinkat";
	syscall_str[SYS_renameat] = "SYS_renameat";
	syscall_str[SYS_linkat] = "SYS_linkat";
	syscall_str[SYS_symlinkat] = "SYS_symlinkat";
	syscall_str[SYS_readlinkat] = "SYS_readlinkat";
	syscall_str[SYS_fchmodat] = "SYS_fchmodat";
	syscall_str[SYS_faccessat] = "SYS_faccessat";
	syscall_str[SYS_pselect6] = "SYS_pselect6";
	syscall_str[SYS_ppoll] = "SYS_ppoll";
	syscall_str[SYS_unshare] = "SYS_unshare";
	syscall_str[SYS_set_robust_list] = "SYS_set_robust_list";
	syscall_str[SYS_get_robust_list] = "SYS_get_robust_list";
	syscall_str[SYS_splice] = "SYS_splice";
	syscall_str[SYS_tee] = "SYS_tee";
	syscall_str[SYS_sync_file_range] = "SYS_sync_file_range";
	syscall_str[SYS_vmsplice] = "SYS_vmsplice";
	syscall_str[SYS_move_pages] = "SYS_move_pages";
	syscall_str[SYS_utimensat] = "SYS_utimensat";
	syscall_str[SYS_epoll_pwait] = "SYS_epoll_pwait";
	syscall_str[SYS_signalfd] = "SYS_signalfd";
	syscall_str[SYS_timerfd_create] = "SYS_timerfd_create";
	syscall_str[SYS_eventfd] = "SYS_eventfd";
	syscall_str[SYS_fallocate] = "SYS_fallocate";
	syscall_str[SYS_timerfd_settime] = "SYS_timerfd_settime";
	syscall_str[SYS_timerfd_gettime] = "SYS_timerfd_gettime";
	syscall_str[SYS_accept4] = "SYS_accept4";
	syscall_str[SYS_signalfd4] = "SYS_signalfd4";
	syscall_str[SYS_eventfd2] = "SYS_eventfd2";
	syscall_str[SYS_epoll_create1] = "SYS_epoll_create1";
	syscall_str[SYS_dup3] = "SYS_dup3";
	syscall_str[SYS_pipe2] = "SYS_pipe2";
	syscall_str[SYS_inotify_init1] = "SYS_inotify_init1";
	syscall_str[SYS_preadv] = "SYS_preadv";
	syscall_str[SYS_pwritev] = "SYS_pwritev";
	syscall_str[SYS_rt_tgsigqueueinfo] = "SYS_rt_tgsigqueueinfo";
	syscall_str[SYS_perf_event_open] = "SYS_perf_event_open";
	syscall_str[SYS_recvmmsg] = "SYS_recvmmsg";
	syscall_str[SYS_fanotify_init] = "SYS_fanotify_init";
	syscall_str[SYS_fanotify_mark] = "SYS_fanotify_mark";
	syscall_str[SYS_prlimit64] = "SYS_prlimit64";
	syscall_str[SYS_name_to_handle_at] = "SYS_name_to_handle_at";
	syscall_str[SYS_open_by_handle_at] = "SYS_open_by_handle_at";
	syscall_str[SYS_clock_adjtime] = "SYS_clock_adjtime";
	syscall_str[SYS_syncfs] = "SYS_syncfs";
	syscall_str[SYS_sendmmsg] = "SYS_sendmmsg";
	syscall_str[SYS_setns] = "SYS_setns";
	syscall_str[SYS_getcpu] = "SYS_getcpu";
	syscall_str[SYS_process_vm_readv] = "SYS_process_vm_readv";
	syscall_str[SYS_process_vm_writev] = "SYS_process_vm_writev";
	syscall_str[SYS_kcmp] = "SYS_kcmp";
	syscall_str[SYS_finit_module] = "SYS_finit_module";
	syscall_str[SYS_sched_setattr] = "SYS_sched_setattr";
	syscall_str[SYS_sched_getattr] = "SYS_sched_getattr";
	syscall_str[SYS_renameat2] = "SYS_renameat2";
	syscall_str[SYS_seccomp] = "SYS_seccomp";
	syscall_str[SYS_getrandom] = "SYS_getrandom";
	syscall_str[SYS_memfd_create] = "SYS_memfd_create";
	syscall_str[SYS_kexec_file_load] = "SYS_kexec_file_load";
	syscall_str[SYS_bpf] = "SYS_bpf";
	syscall_str[SYS_execveat] = "SYS_execveat";
	syscall_str[SYS_userfaultfd] = "SYS_userfaultfd";
	syscall_str[SYS_membarrier] = "SYS_membarrier";
	syscall_str[SYS_mlock2] = "SYS_mlock2";
	syscall_str[SYS_copy_file_range] = "SYS_copy_file_range";
	syscall_str[SYS_preadv2] = "SYS_preadv2";
	syscall_str[SYS_pwritev2] = "SYS_pwritev2";
	syscall_str[SYS_pkey_mprotect] = "SYS_pkey_mprotect";
	syscall_str[SYS_pkey_alloc] = "SYS_pkey_alloc";
	syscall_str[SYS_pkey_free] = "SYS_pkey_free";
	syscall_str[SYS_statx] = "SYS_statx";
	syscall_str[SYS_io_pgetevents] = "SYS_io_pgetevents";
	syscall_str[SYS_rseq] = "SYS_rseq";
	syscall_str[SYS_pidfd_send_signal] = "SYS_pidfd_send_signal";
	syscall_str[SYS_io_uring_setup] = "SYS_io_uring_setup";
	syscall_str[SYS_io_uring_enter] = "SYS_io_uring_enter";
	syscall_str[SYS_io_uring_register] = "SYS_io_uring_register";
	syscall_str[SYS_open_tree] = "SYS_open_tree";
	syscall_str[SYS_move_mount] = "SYS_move_mount";
	syscall_str[SYS_fsopen] = "SYS_fsopen";
	syscall_str[SYS_fsconfig] = "SYS_fsconfig";
	syscall_str[SYS_fsmount] = "SYS_fsmount";
	syscall_str[SYS_fspick] = "SYS_fspick";
	syscall_str[SYS_pidfd_open] = "SYS_pidfd_open";
	syscall_str[SYS_clone3] = "SYS_clone3";
}

#endif